services:
  nextjs:
    build: ./OpenLAB-Web-FE
    container_name: nextjs
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./OpenLAB-Web-FE/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nextjs
    restart: always

  root_api:
    build: ./http-gateway-api
    container_name: http-gateway-api
    ports:
      - "3001:3001"
    volumes:
      - ./http-gateway-api/src:/usr/src/app/src
    command: npm run start:prod
    environment:
      - PORT=3001
      - URL_REACT_CLIENT=http://localhost
    depends_on:
      - nats
    restart: always

  auth_service:
    build: ./auth-service
    container_name: auth-service
    volumes:
      - ./auth-service/src:/usr/src/app/src
    command: npm run start:prod
    depends_on:
      - nats
      - mongo_db
    restart: always

  contact_service:
    build: ./contact-mailer
    container_name: contact-service
    volumes:
      - ./contact-mailer/src:/usr/src/app/src
    command: npm run start:prod
    depends_on:
      - nats
      - mongo_db
    restart: always

  # course_service:
  #   build: ./course-service
  #   container_name: course-service
  #   volumes:
  #     - ./course-service/src:/usr/src/app/src
  #   command: npm run start:prod
  #   depends_on:
  #     - nats
  #     - mongo_db
  #   restart: always

  payments_service:
    build: ./payments-service
    container_name: payments-service
    volumes:
      - ./payments-service/src:/usr/src/app/src
    command: npm run start:prod
    depends_on:
      - nats
      - mongo_db
    restart: always

  nats:
    image: nats
    ports:
      - "4222:4222"
    container_name: nats
    restart: always

  mongo_db:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456789
    volumes:
      - mongo_data:/data/db
      - ./mongo-init-scripts:/docker-entrypoint-initdb.d
    restart: always
volumes:
  mongo_data:
    driver: local
